drop table if exists tb_brand cascade
create table tb_brand (
      id bigint generated by default as identity,
      description varchar(255),
      name varchar(255) not null,
      primary key (id)
)