version: '3.8'

services:
  cache:
    container_name: cache
    platform: linux/amd64
    image: redis:6.2.1
    ports:
      - "6379:6379"

  database:
    container_name: database
    platform: linux/amd64
    image: mysql:8.0.23
    ports:
      - "3306:3306"
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=jwt
      - MYSQL_USER=jwt
      - MYSQL_PASSWORD=jwt
      - TZ=Asia/Seoul
    volumes:
      - ./mysql/volume:/var/lib/mysql