version: '3.8'

services:
  mysql:
    container_name: mysql
    platform: linux/amd64
    image: mysql:5.7
    ports:
      - "3388:3306"
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --log-bin-trust-function-creators=1
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=okkot
      - MYSQL_USER=okkot
      - MYSQL_PASSWORD=okkot
      - TZ=Asia/Seoul
    volumes:
      - ./mysql/init.d:/docker-entrypoint-initdb.d
      - ./mysql/volume:/var/lib/mysql
    networks:
      - docker-database

  redis:
    container_name: redis
    platform: linux/amd64
    image: redis:7.0.7
    ports:
      - "6388:6379"
    volumes:
      - ./redis/volume:/data
    networks:
      - docker-database

networks:
  docker-database:
    driver: bridge