version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "concurrency"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
