spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt
    username: jwt
    password: jwt


  flyway:
    enabled: false
    baselineOnMigrate: false
    locations:
      - classpath:db/migration/{vendor}
      - classpath:db/seed/local

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  output:
    ansi:
      enabled: always

server:
  port: 8080

jwt:
  secret: and0LWV4YW1wbGUtYWNjZXNzLXRva2VuLXNlY3JldC1rZXk=
  # 2시간 = 2 * 60 * 60 * 1000
  access-token-expire-time: 720000

  refresh-secret: and0LWV4YW1wbGUtcmVmcmVzaC10b2tlbi1zZWNyZXQta2V5
  # 2주 = 14 * 24 * 60 * 60 * 1000
  refresh-token-expire-time: 1209600000
