spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/jwt
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: jwt
      password: jwt


  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  output:
    ansi:
      enabled: always

server:
  port: 8080

jwt:
  secret: WjJaa1ptZGtabXhyWjJwa2JHWnJaMnB6WVhOa2FtdG9ZWE5yWkdwaGFITmthMnBoYUhOa0NnZ2ZkZmdkZmxrZ2pkbGZrZ2pzYXNkamtoYXNrZGphaHNka2phaHNkCg
  access-token-expire-time: 1800000
  refresh-token-expire-time: 1800000
